config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.per_page = 2
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  mount_uploader :picture, PictureUploader

  RATINGS = {
    '☻': '1_star',
    '☻☻': '2_star',
    '☻☻☻': '3_star',
    '☻☻☻☻': '4_star',
    '☻☻☻☻☻': '5_star'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  geocoded_by :address
  after_validation :geocode
  validates :name, :address, :description, presence: true
  validates :name, length: {minimum: 3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!


  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  def edit
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      return render plain: 'Not allowed', status: :forbidden
    end
  end
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      return render plain: 'Not allowed', status: :forbidden
    end
    @comment.update_attributes(comment_params)
    if @comment.valid?
      redirect_to user_path(current_user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:place_id])
    if @comment.user != current_user
      return render plain: 'Not allowed', status: :forbidden
    end
    @comment.destroy
    redirect_to user_path(current_user)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating, :picture, :caption)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all
    @places = Place.paginate(page: params[:page], per_page: 2)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to place_path(@place)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not allowed', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not allowed', status: :forbidden
    end
    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to place_path(@place)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not allowed', status: :forbidden
    end
    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit a Comment</h1>
  <br />
  <%= simple_form_for ([@comment.place, @comment]) do |f| %>
    <%= f.input :message, label: false, placeholder: 'message', input_html: { maxlength: 50} %> 
    <%= f.input :rating, label: false, as: :select, collection: Comment::RATINGS, prompt: "Select rating" %>
    <%= f.input :picture, label: false %> 
    <%= f.input :caption, label: false, placeholder: 'caption', input_html: { maxlength: 30} %>
    <%= f.submit 'Update', class: 'btn btn-primary' %>
    <%= link_to 'Delete', place_comment_path(@comment), method: :delete, data: {confirm: 'Are you sure you want to delete is entry?'}, class: 'btn btn-primary float-right' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BreweryRadar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'BreweryRadar', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              Add a Brewery
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit a Brewery</h1>
  <br />
  <%= simple_form_for @place do |f| %>
    <%= f.input :name, required: true, label: false, placeholder: 'Name' %>
    <%= f.input :address, required: true, label: false, placeholder: 'Address' %>
    <%= f.input :description, required: true, label: false, placeholder: 'Description' %>
    <%= f.submit 'Update', class: 'btn btn-primary' %>
    <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete is entry?'},  class: 'btn btn-primary float-right' %>
  <% end %>
</div>

app/views/places/index.html.erb
<!-- Carousel -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active slider1">
      <%= image_tag 'clear.png', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        Find the best Breweries in town
      </div>
    </div>
    <div class="carousel-item slider2">
      <%= image_tag 'clear.png', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
         Rate the Brewery and Beer
      </div>
    </div>
    <div class="carousel-item slider3">
      <%= image_tag 'clear.png', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
         Comment and Post pictures
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="clear"></div>

<!-- Pagination -->
<div class="col-10 offset-1">
  <div class="digg_pagination">
    <%= will_paginate @places %>
  </div>
</div>

<!-- Place -->
<% @places.each do |place| %>

  <div class="booyah-box col-10 offset-1">
    <div class="percent-flex">
      <div>
        <h1><%= link_to place.name, place_path(place) %></h1>
        <i><%= place.address %></i>
        <br />
        <br />
        <p><%= place.description %></p>
        <% if place.user.present? %>
          <small><b>User#<%= place.user_id %></b></small>
        <% end %>
      </div>

<!-- Last comment -->
      <div> 
        <% if place.comments.present? %>
          <blockquote>
            User#<%= place.comments.last.user_id %> -        
            <% if place.comments.last.humanized_rating.present? %>        
              <b class="stars"><%= place.comments.last.humanized_rating %></b>
            <% end %>
          </blockquote>
          <div class="user-img-box-last">
            <div class="user-img" style="background-image: url(<%= place.comments.last.picture.url %>);">
              <%= image_tag("clear.png") %>            
            </div>            
          </div>
          <blockquote>
            <%= place.comments.last.caption %>              
          </blockquote>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="clear"></div>

<!-- Pagination -->
<div class="col-10 offset-1">
  <div class="digg_pagination">
    <%= will_paginate @places %>
  </div>
</div>

<div class="clear"></div>



app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Add a Brewery</h1>
  <br />
  <%= simple_form_for @place do |f| %>
    <%= f.input :name, required: true, label: false, placeholder: 'Name' %>
    <%= f.input :address, required: true, label: false, placeholder: 'Address' %>
    <%= f.input :description, required: true, label: false, placeholder: 'Description' %>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
</div>
  

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">  

 <!-- Show place -->  
  <h1><%= @place.name %></h1> 
  <i><%= @place.address %></i><br /><br />  
  <p><%= @place.description %><br />
  <small><b>User#<%= @place.user_id %></b></small></p>

 <!-- Geocoding map --> 
  <% if @place.latitude.present? && @place.longitude.present? %>  
    <script>  
      function initMap() {  
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>}; 
        var map = new google.maps.Map(document.getElementById('map'), { 
          zoom: 16, 
          center: myLatLng  
        }); 
        var marker = new google.maps.Marker({ 
          position: myLatLng, 
          map: map, 
          title: 'Hello World!' 
        }); 
      } 
    </script> 
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=GEOCODER_API_KEY&callback=initMap"></script>      
  <% end %>
  <div id="map"></div> 

   <br /> 

 <!-- Button trigger modal -->  
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal"> 
    Add a comment 
  </button> 

 <!-- Check user login -->  
  <% if current_user && current_user == @place.user %>  
    <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary float-right' %>  
  <% end %> 

 </div> 

 <!-- Modal --> 
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> 
  <div class="modal-dialog" role="document">  
    <div class="modal-content"> 
      <div class="modal-header">  
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">  
          <span aria-hidden="true">×</span> 
        </button> 
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>  
      </div>

<!-- Add comment --> 
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>  
        <div class="modal-body">  
          <%= f.input :message, label: false, placeholder: 'message' %> 
          <%= f.input :rating, label: false, as: :select, collection: Comment::RATINGS, prompt: "Select rating" %>

<!-- Add picture --> 
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">  
              <span aria-hidden="true">×</span> 
            </button>
            <h4 class="modal-title" id="myModalLabel">Add a picture</h4>
          </div>
          <%= f.input :picture, label: false %> 
          <%= f.input :caption, label: false, placeholder: 'caption' %> 
        </div>  
        <div class="modal-footer">  
          <%= f.submit 'Enter', class: 'btn btn-primary' %> 
        </div>  
      <% end %> 

     </div> 
  </div>  
</div>

 <!-- Comments -->  
<div class="user-comment">  
  <% @place.comments.each do |comment| %>
    <div class="booyah-box col-10 col-sm-5 offset-1 float-left">  
      <blockquote>  
        User#<%= comment.user_id %> -         
        <% if comment.humanized_rating.present? %>            
          <span class="stars"><%= comment.humanized_rating %></span> -  
        <% end %> 
        <%= comment.caption %>  
      </blockquote>
      <div class="user-img-box">  
        <div class="user-img" style="background-image: url(<%= comment.picture.url %>);"> 
          <%= image_tag("clear.png") %>             
        </div>  
        <blockquote class="user-caption"> 
          <%= comment.message %>                
        </blockquote> 
      </div>   
    </div>  
  <% end %> 
</div>

app/views/users/show.html.erb
<!-- User info -->
<div class="booyah-box col-10 offset-1">
  <div class="percent-flex">
    <div>
      <h4><%= @user.email %></h4>
      <br />
      <p>
        Member Since: <%= @user.created_at.strftime("%B %d, %Y") %><br />
        <%= @user.comments.count %> total comments<br />
        <%= @user.comments.where(rating: '5_star').count %> total <span class="stars">☻☻☻☻☻</span> reviews
    </p>
    </div>
    <div>
      <div class="user_pic"><%= image_tag 'user.png' %></div>
    </div>
  </div>
</div>

<!-- Comments -->
<div class="full-width">
  <div class="booyah-box col-10 offset-1">
    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#comments">Comments</button>
  </div>
</div>

<div id="comments" class="user-comment collapse in">  
  <% @user.comments.each do |comment| %> 
    <div class="booyah-box col-10 col-sm-5 offset-1 float-left">
      <blockquote>  
        User#<%= comment.user_id %> -         
        <% if comment.humanized_rating.present? %>            
          <span class="stars"><%= comment.humanized_rating %></span> -  
        <% end %> 
        <%= comment.caption %>  
      </blockquote>
      <div class="user-img-box">  
        <div class="user-img" style="background-image: url(<%= comment.picture.url %>);"> 
          <%= image_tag("clear.png") %>             
        </div>  
        <blockquote class="user-caption"> 
          <%= comment.message %>                
        </blockquote>
        <div class="percent-2"></div>
        <% if @user.comments.present? %>
        <div class="center">        
          <%= link_to 'Edit', edit_place_comment_path(comment.place, comment), class: 'btn btn-primary float-left' %>          
          <%= link_to comment.place.name, place_path(comment.place) %>
          <%= link_to 'Delete', place_comment_path(comment), method: :delete, data: {confirm: 'Are you sure you want to delete is entry?'}, class: 'btn btn-primary float-right' %>
        </div>
        <% end %>          
      </div>
        
    </div>  
  <% end %> 
</div>

<div class="clear"></div>

<!-- Breweries -->
<div class="booyah-box col-10 offset-1">
    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#breweries">Breweries</button>
</div>

<div id="breweries" class="user-comment collapse">  
  <% @user.places.each do |place| %> 
    <div class="booyah-box col-10 offset-1 float-left">
      <h1><%= link_to place.name, place_path(place) %></h1>
      <i><%= place.address %></i>
      <br />
      <br />
      <p><%= place.description %></p>
      <% if place.user.present? %>
        <small><b>User#<%= place.user_id %></b></small>
      <% end %>
      <%= link_to 'Edit', edit_place_path(place), class: 'btn btn-primary' %>
      <%= link_to 'Delete', place_path(place), method: :delete, data: {confirm: 'Are you sure you want to delete is entry?'},  class: 'btn btn-primary float-right' %>
    </div>
  <% end %> 
</div>